# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  tag: 0.0.$(Build.BuildId)
  dockerhubrepositoryname: sulabh4

pool:
  vmImage: Default #ubuntu-latest

stages:
- stage: Build
  displayName: Build and Push Docker Images
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub Codexponent'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub Codexponent'
        repository: '$(dockerhubrepositoryname)/siri-lambda'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)

    
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS Codexponent'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: '$(dockerhubrepositoryname)/siri-lambda:$(tag)'
        repositoryName: '$(ec2-repo-name)/siri-lambda:$(tag)'