# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: Default #ubuntu-latest

stages:
- stage: Build
  displayName: Build and Push Docker Images
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub Codexponent'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub Codexponent'
        repository: 'siri-lambda'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'